apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-helm-values
  namespace: kube-system
data:
  values.yaml: |
    # NOTE: Sourced from values/cilium-full.yaml
    kubeProxyReplacement: true
    ipam:
      mode: kubernetes
    l7Proxy: true

    gatewayAPI:
      enabled: true
      enableAlpn: true
      enableAppProtocol: true

    ingressController:
      enabled: true

    service:
      lb:
        acceleration: "best-effort"

    bgpControlPlane:
      enabled: true

    egressGateway:
      enabled: true
    bpf:
      masquerade: true

    bandwidthManager:
      enabled: true
      bbr: true

    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true

    prometheus:
      enabled: true
    operator:
      prometheus:
        enabled: true

    hostFirewall:
      enabled: true

    dnsProxy:
      enableTransparentMode: true

    multicast:
      enabled: true

    encryption:
      enabled: true
      type: wireguard

    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    k8sServiceHost: localhost
    k8sServicePort: 7445
