apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-helm-values
  namespace: cilium-system
data:
  values.yaml: |-
    # Cilium Helm values enabling requested features
    kubeProxyReplacement: disabled
    k8sServiceHost: ""
    k8sServicePort: ""

    cni:
      customConf: false
      exclusive: true
      install: true

    ipam:
      mode: kubernetes

    routingMode: tunnel
    autoDirectNodeRoutes: false

    encryption:
      enabled: false

    containerRuntime:
      integration: none

    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
          - http
      relay:
        enabled: true
      ui:
        enabled: true

    loadBalancer:
      acceleration: disabled
      algorithm: maglev
      mode: snat

    ingressController:
      enabled: true
      loadbalancerMode: shared
      default: true

    gatewayAPI:
      enabled: true
      enableRequestAuthenticationFilter: true

    bgpControlPlane:
      enabled: true
    bgp:
      enabled: true

    k8sClientRateLimit:
      qps: 50
      burst: 100

    nodeinit:
      enabled: false

    operator:
      replicas: 1
      rollOutPods: true

    resources:
      limits: {}
      requests: {}

    hostServices:
      enabled: true
    externalIPs:
      enabled: true
    nodePort:
      enabled: true

    ipv4:
      enabled: true
    ipv6:
      enabled: false

    bpf:
      autoMount:
        enabled: false
