apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.6.x
    helm:
      valueFiles:
        - gitops/argocd/apps/longhorn/values.yaml
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
