---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, infraflux-admins, role:admin
    g, infraflux-readers, role:readonly
  scopes: "[email, groups]"
