# Starter sync that applies the "base" recipe bundle from this repo.
# Safe to keep in the mgmt cluster; adjust the path if you prefer a different bootstrap set.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infraflux-recipes-base
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: infraflux
  path: ./recipes/base
  # Optionally target a specific namespace for generated objects that don't declare one
  targetNamespace: flux-system
  timeout: 5m
