apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  # Flux core components get exported here by `flux install --export`
  - gotk-components.yaml

  # Namespace
  - namespace.yaml

  # Git source that points Flux at this repo (starter)
  - sources/git/infraflux.yaml

  # Common Helm repositories used by InfraFlux recipes
  - sources/helm/cilium.yaml
  - sources/helm/jetstack.yaml
  - sources/helm/bitnami.yaml
  - sources/helm/prometheus-community.yaml
  - sources/helm/argo.yaml
  - sources/helm/longhorn.yaml
  - sources/helm/envoy-gateway.yaml

  # Optional: a starter sync to the base recipes (safe to keep; adjust as needed)
  - gotk-sync.yaml
