apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  # Flux core (filled by `flux install --export`)
  - gotk-components.yaml

  # Namespace
  - namespace.yaml

  # Git source pointing to this repo
  - sources/git/infraflux.yaml

  # Common Helm repositories
  - sources/helm/cilium.yaml
  - sources/helm/jetstack.yaml
  - sources/helm/bitnami.yaml
  - sources/helm/prometheus-community.yaml
  - sources/helm/argo.yaml
  - sources/helm/longhorn.yaml
  - sources/helm/envoy-gateway.yaml

  # NEW: extra catalogs
  - sources/helm/grafana.yaml
  - sources/helm/ingress-nginx.yaml
  - sources/helm/hashicorp.yaml

  # Kustomizations to sync recipes
  - gotk-sync.yaml # base bundle
  - gotk-sync-observability.yaml # observability bundle
  - gotk-sync-devtools.yaml # devtools bundle
