# Auto-generated Ansible inventory for RKE2 cluster
# Generated by Terraform on ${timestamp()}

[servers]
%{ for server in servers ~}
${server.name} ansible_host=${server.ip}
%{ endfor ~}

[agents]
%{ for agent in agents ~}
${agent.name} ansible_host=${agent.ip}
%{ endfor ~}

[rke2]

[rke2:children]
servers
agents

[rke2:vars]
ansible_user=${ansible_user}
ansible_become=true
ansible_become_method=sudo
ansible_ssh_private_key_file=~/.ssh/id_rsa
