# Auto-generated Ansible configuration for RKE2 deployment
# Generated by Terraform on ${timestamp()}

[defaults]
host_key_checking = False
inventory = ansible/RKE2/inventory/hosts.ini
remote_user = ${ansible_user}
private_key_file = ${ssh_private_key_file}
timeout = 30
gathering = smart
fact_caching = memory
roles_path = ansible/RKE2/roles
collections_path = ansible/RKE2/collections
retry_files_enabled = False
stdout_callback = yaml

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR
pipelining = True
host_key_checking = False

[privilege_escalation]
become = True
become_method = sudo
become_ask_pass = False
