site_name: InfraFlux
site_description: One-command, multi-cloud Kubernetes recipes with Cluster API, Talos, Cilium, and Flux.
repo_url: https://github.com/your-org/infraflux
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - content.tabs.link
    - toc.integrate
    - search.suggest
    - search.highlight
nav:
  - Overview: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Architecture: architecture.md
  - GitOps & Repos: gitops.md
  - Networking: networking.md
  - Recipes: recipes.md
  - Secrets (SOPS): secrets.md
  - Crossplane: crossplane.md
  - Providers:
      - Common Prereqs: providers/common-prereqs.md
      - AWS: providers/aws.md
      - Azure: providers/azure.md
      - GCP: providers/gcp.md
      - Proxmox: providers/proxmox.md
  - CLI Reference: cli.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
