apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 12h
  chart:
    spec:
      chart: traefik
      version: ">=36.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: traefik-helm-chart-value-overrides
      valuesKey: values.yaml
      optional: false
  upgrade:
    remediation:
      retries: 3
  install:
    timeout: 10m
  upgrade:
    timeout: 10m