# RKE2 Kubernetes Cluster Deployment Playbook
# Deploys a highly available RKE2 cluster with kube-vip for control plane HA
############################################################

# Prepare all nodes
- name: Prepare all nodes
  hosts: rke2
  gather_facts: true
  become: true
  roles:
    - prepare-nodes
    - rke2-download

# Deploy Kube-VIP for control plane high availability
- name: Deploy Kube VIP
  hosts: servers
  gather_facts: true
  become: true
  roles:
    - kube-vip

# Prepare RKE2 configuration on all nodes
- name: Prepare RKE2 on Servers and Agents
  hosts: servers,agents
  gather_facts: true
  become: true
  roles:
    - rke2-prepare

# Fetch and share RKE2 token across all hosts
- name: Fetch and share RKE2 token
  hosts: servers,agents
  gather_facts: false
  become: true
  tasks:
    - name: Fetch the token from the first server node
      ansible.builtin.slurp:
        src: /var/lib/rancher/rke2/server/node-token
      register: rke2_token
      when: inventory_hostname == groups['servers'][0]
      run_once: true

    - name: Save Master node-token as fact on first server
      ansible.builtin.set_fact:
        token: "{{ rke2_token['content'] | b64decode | regex_replace('\n', '') }}"
      when:
        - inventory_hostname == groups['servers'][0]
        - rke2_token is defined

    - name: Share token with all other hosts
      ansible.builtin.set_fact:
        token: "{{ hostvars[groups['servers'][0]]['token'] }}"
      when:
        - inventory_hostname != groups['servers'][0]
        - hostvars[groups['servers'][0]]['token'] is defined

# Add additional servers to the cluster
- name: Add additional RKE2 Servers
  hosts: servers
  gather_facts: true
  become: true
  roles:
    - add-server

# Add agent nodes to the cluster
- name: Add additional RKE2 Agents
  hosts: agents
  gather_facts: true
  become: true
  roles:
    - add-agent

# Final cluster validation
- name: Validate cluster deployment
  hosts: servers[0]
  gather_facts: true
  become: true
  roles:
    - cluster-validate

# Download and configure kubeconfig for local access
- name: Configure kubeconfig for local access
  hosts: servers[0]
  gather_facts: true
  become: false
  roles:
    - kubeconfig-manager
