# RKE2 Kubernetes Cluster Deployment Playbook
# Deploys a highly available RKE2 cluster with kube-vip for control plane HA
############################################################

# Prepare all nodes (servers and agents)
- name: Add SSH host keys for all VMs
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Get current user's home directory
      ansible.builtin.set_fact:
        user_home: "{{ lookup('env', 'HOME') }}"

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "{{ user_home }}/.ssh"
        state: directory
        mode: '0700'

    - name: Scan and add server SSH host keys to known_hosts
      ansible.builtin.shell: |
        ssh-keyscan -H {{ hostvars[item]['ansible_host'] | default(item) }} >> {{ user_home }}/.ssh/known_hosts 2>/dev/null || true
      loop: "{{ groups['servers'] }}"
      changed_when: false

    - name: Scan and add agent SSH host keys to known_hosts
      ansible.builtin.shell: |
        ssh-keyscan -H {{ hostvars[item]['ansible_host'] | default(item) }} >> {{ user_home }}/.ssh/known_hosts 2>/dev/null || true
      loop: "{{ groups['agents'] }}"
      changed_when: false

    - name: Remove duplicate entries from known_hosts
      ansible.builtin.shell: |
        sort -u {{ user_home }}/.ssh/known_hosts > {{ user_home }}/.ssh/known_hosts.tmp && mv {{ user_home }}/.ssh/known_hosts.tmp {{ user_home }}/.ssh/known_hosts
      changed_when: false

- name: Prepare all nodes
  hosts: rke2
  gather_facts: true
  become: true
  roles:
    - prepare-nodes
    - rke2-download

# Deploy Kube-VIP for control plane high availability
- name: Deploy Kube VIP
  hosts: servers
  gather_facts: true
  become: true
  roles:
    - kube-vip

# Prepare RKE2 configuration on all nodes
- name: Prepare RKE2 on Servers and Agents
  hosts: servers,agents
  gather_facts: true
  become: true
  roles:
    - rke2-prepare

# Add additional servers to the cluster
- name: Add additional RKE2 Servers
  hosts: servers
  gather_facts: true
  become: true
  roles:
    - add-server

# Add agent nodes to the cluster
- name: Add additional RKE2 Agents
  hosts: agents
  gather_facts: true
  become: true
  roles:
    - add-agent

# Final cluster validation and setup
- name: Validate cluster and complete setup
  hosts: servers[0]
  gather_facts: true
  become: true
  roles:
    - apply-manifests

# Download and configure kubeconfig for local access
- name: Configure kubeconfig for local access
  hosts: servers[0]
  gather_facts: true
  become: true
  roles:
    - kubeconfig-manager
