apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-project
    app.kubernetes.io/component: gitops
spec:
  description: Platform infrastructure components
  sourceRepos:
    - 'https://github.com/binGhzal/infraflux'
    - 'https://helm.cilium.io'
    - 'https://charts.jetstack.io'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'
    - 'https://kubernetes-sigs.github.io/external-dns'
    - 'https://longhorn.github.io/charts'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: Node
    - group: ''
      kind: PersistentVolume
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionWebhook
    - group: admissionregistration.k8s.io
      kind: MutatingAdmissionWebhook
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodSecurityPolicy
    - group: security.istio.io
      kind: PeerAuthentication
    - group: cilium.io
      kind: CiliumNetworkPolicy
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: apps
      kind: '*'
    - group: batch
      kind: '*'
    - group: networking.k8s.io
      kind: '*'
    - group: policy
      kind: '*'
    - group: cert-manager.io
      kind: '*'
    - group: monitoring.coreos.com
      kind: '*'
  roles:
    - name: platform-admin
      description: Admin access to platform infrastructure
      policies:
        - p, proj:platform:platform-admin, applications, *, platform/*, allow
        - p, proj:platform:platform-admin, repositories, *, *, allow
      groups:
        - platform-team
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  labels:
    app.kubernetes.io/name: applications-project
    app.kubernetes.io/component: gitops
spec:
  description: Application workloads and services
  sourceRepos:
    - 'https://github.com/binGhzal/PlatformNorthStar'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://helm.releases.hashicorp.com'
    - 'https://kubernetes.github.io/ingress-nginx'
  destinations:
    - namespace: 'app-*'
      server: https://kubernetes.default.svc
    - namespace: 'workload-*'
      server: https://kubernetes.default.svc
    - namespace: 'service-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: [] # Applications cannot create cluster resources
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: apps
      kind: '*'
    - group: batch
      kind: '*'
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
  roles:
    - name: app-developer
      description: Developer access to application deployments
      policies:
        - p, proj:applications:app-developer, applications, *, applications/*, allow
        - p, proj:applications:app-developer, repositories, get, https://github.com/binGhzal/PlatformNorthStar, allow
      groups:
        - developers
    - name: app-admin
      description: Admin access to all applications
      policies:
        - p, proj:applications:app-admin, applications, *, applications/*, allow
        - p, proj:applications:app-admin, repositories, *, *, allow
      groups:
        - platform-team
        - devops-team
