services:
  decypharr:
    restart: unless-stopped
    container_name: decypharr
    image: cy01/blackhole:latest
    hostname: decypharr
    ports:
      - "8282:8282" # qBittorrent API emulation
      - "8181:8181" # Proxy service
    environment:
      - PUID=1000
      - PGID=1000
      - QBIT_PORT=8282 # Optional: QBittorrent port
      - PORT=8181 # Optional: Proxy port
      - UMASK=000
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.decypharr-http.entrypoints: web
      traefik.http.routers.decypharr-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker,authentik@docker
      traefik.http.routers.decypharr-http.rule: Host(`decypharr.binghzal.com`)
      traefik.http.routers.decypharr-http.service: decypharr
      traefik.http.routers.decypharr.entrypoints: websecure
      traefik.http.routers.decypharr.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker,authentik@docker
      traefik.http.routers.decypharr.rule: Host(`decypharr.binghzal.com`)
      traefik.http.routers.decypharr.service: decypharr
      traefik.http.routers.decypharr.tls.certresolver: cfdns
      traefik.http.routers.decypharr.tls.options: securetls@file
      traefik.http.services.decypharr.loadbalancer.server.port: 8282
    volumes:
      - /opt/decypharr:/app:rw
      - /mnt:/mnt:rw

networks:
  saltbox:
    external: true
