apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
    name: example-lab
    namespace: default
spec:
    clusterNetwork:
        pods:
            cidrBlocks: [ "10.244.0.0/16" ]
        services:
            cidrBlocks: [ "10.96.0.0/12" ]
    controlPlaneRef:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: TalosControlPlane
        name: example-lab-control-plane
    infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ProxmoxCluster # e.g., AWSCluster, AzureCluster, GCPCluster, ProxmoxCluster
        name: example-lab
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: TalosConfigTemplate
metadata:
    name: example-lab-worker-template
    namespace: default
spec:
    template:
        spec:
            talosVersion: v1.7.5
            generateType: "join"
