apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
    name: example-lab-md-0
    namespace: default
spec:
    template:
        spec:
            providerID: t3.large
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
    name: example-lab-md-0
    namespace: default
spec:
    clusterName: example-lab
    replicas: 2
    selector:
        matchLabels:
            cluster.x-k8s.io/deployment-name: example-lab-md-0
    template:
        metadata:
            labels:
                cluster.x-k8s.io/deployment-name: example-lab-md-0
        spec:
            bootstrap:
                configRef:
                    apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
                    kind: TalosConfigTemplate
                    name: example-lab-worker-template
            clusterName: example-lab
            infrastructureRef:
                apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
                kind: AWSMachineTemplate
                name: example-lab-md-0
            version: v1.30.0
