---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: cilium-gateway
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.yourdomain.com"  # TODO: Replace with actual domain
    - "yourdomain.com"    # TODO: Replace with actual domain
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days before expiry
