---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: cilium-gateway
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.{{ cloudflare_domain }}"
    - "{{ cloudflare_domain }}"
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days before expiry
