---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 12h
  chart:
    spec:
      chart: cert-manager
      version: ">=1.18.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-helm-chart-value-overrides
      valuesKey: values.yaml
      optional: false
  upgrade:
    remediation:
      retries: 3
