---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-promtail
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      values: |
        loki:
          persistence:
            enabled: false
        promtail:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
