---
# RKE2 Prepare Role Variables
ansible_user: "{{ ansible_user | default('ubuntu') }}"
rke2_install_dir: "{{ rke2_install_dir | default('/usr/local/bin') }}"
rke2_version: "{{ rke2_version | default('v1.29.4+rke2r1') }}"