apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
    name: ${CLUSTER_NAME}
    namespace: ${NAMESPACE}
spec:
    clusterNetwork:
        pods:
            cidrBlocks: [ "10.244.0.0/16" ]
        services:
            cidrBlocks: [ "10.96.0.0/12" ]
    controlPlaneRef:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: TalosControlPlane
        name: ${CLUSTER_NAME}-control-plane
    infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ${INFRA_CLUSTER_KIND} # e.g., AWSCluster, AzureCluster, GCPCluster, ProxmoxCluster
        name: ${CLUSTER_NAME}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: TalosConfigTemplate
metadata:
    name: ${CLUSTER_NAME}-worker-template
    namespace: ${NAMESPACE}
spec:
    template:
        spec:
            talosVersion: ${TALOS_VERSION}
            generateType: "join"
