apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: TalosControlPlane
metadata:
    name: ${CLUSTER_NAME}-control-plane
    namespace: ${NAMESPACE}
spec:
    replicas: ${CP_COUNT}
    version: v${K8S_MINOR}.0
    infrastructureTemplate:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ${INFRA_MACHINE_TEMPLATE_KIND} # e.g., AWSMachineTemplate, ProxmoxMachineTemplate
        name: ${CLUSTER_NAME}-cp
    talosConfig:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
        kind: TalosConfigTemplate
        name: ${CLUSTER_NAME}-cp-template
