apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ${INFRA_MACHINE_TEMPLATE_KIND}
metadata:
    name: ${CLUSTER_NAME}-md-0
    namespace: ${NAMESPACE}
spec:
    template:
        spec:
            providerID: ${PROVIDER_SPEC_WORKER}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
    name: ${CLUSTER_NAME}-md-0
    namespace: ${NAMESPACE}
spec:
    clusterName: ${CLUSTER_NAME}
    replicas: ${WORKER_COUNT}
    selector:
        matchLabels:
            cluster.x-k8s.io/deployment-name: ${CLUSTER_NAME}-md-0
    template:
        metadata:
            labels:
                cluster.x-k8s.io/deployment-name: ${CLUSTER_NAME}-md-0
        spec:
            bootstrap:
                configRef:
                    apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
                    kind: TalosConfigTemplate
                    name: ${CLUSTER_NAME}-worker-template
            clusterName: ${CLUSTER_NAME}
            infrastructureRef:
                apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
                kind: ${INFRA_MACHINE_TEMPLATE_KIND}
                name: ${CLUSTER_NAME}-md-0
            version: v${K8S_MINOR}.0
