# kube-prometheus-stack values
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
# Enable Grafana sidecar dashboards
grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /var/lib/grafana/dashboards
    datasources:
      enabled: true
prometheus:
  serviceMonitorSelectorNilUsesHelmValues: false
  podMonitorSelectorNilUsesHelmValues: false
