---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-helm-chart-value-overrides
  namespace: longhorn-system
data:
  values.yaml: |
    # Longhorn default settings
    defaultSettings:
      backupTarget: ""
      backupTargetCredentialSecret: ""
      createDefaultDiskLabeledNodes: true
      defaultDataPath: "/var/lib/longhorn/"
      replicaSoftAntiAffinity: false
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      upgradeChecker: false
      defaultReplicaCount: 3
      guaranteedEngineCPU: 0.25
      defaultLonghornStaticStorageClass: longhorn
      backupstorePollInterval: 300
      taintToleration: ""
      systemManagedComponentsNodeSelector: ""
      priorityClass: ""
      autoSalvage: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      disableSchedulingOnCordonedNode: true
      replicaZoneSoftAntiAffinity: true
      volumeAttachmentRecoveryPolicy: wait
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      mkfsExt4Parameters: ""

    # Persistence settings
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Retain

    # Ingress for Longhorn UI
    ingress:
      enabled: false
      # Enable and configure if you want web UI access
      # host: longhorn.example.com
      # annotations:
      #   traefik.ingress.kubernetes.io/router.tls: "true"
      #   cert-manager.io/cluster-issuer: letsencrypt-prod

    # Service configuration
    service:
      ui:
        type: ClusterIP
        port: 80
      manager:
        type: ClusterIP
        port: 9500

    # Resource settings
    longhornManager:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi

    longhornDriver:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi

    longhornUI:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
