---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 12h
  chart:
    spec:
      chart: longhorn
      version: ">=1.9.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-helm-chart-value-overrides
      valuesKey: values.yaml
      optional: false
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  install:
    timeout: 10m
