apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.14.4 # pinned; update as needed
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    serviceAccount:
      create: true
      name: external-dns
    policy: upsert-only
    registry: txt
    txtOwnerId: infraflux
    logLevel: info
    provider: aws # change per environment; without credentials the pod will error until configured
    sources:
      - service
      - ingress
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: external-dns-aws-creds
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-aws-creds
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_REGION
        valueFrom:
          secretKeyRef:
            name: external-dns-aws-creds
            key: AWS_REGION
