---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: SecretStore
  target:
    name: velero-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .accessKeyID }}
          aws_secret_access_key={{ .secretAccessKey }}
  data:
    - secretKey: accessKeyID
      remoteRef:
        key: "infraflux-prod/velero-minio"
        property: "access_key_id"
    - secretKey: secretAccessKey
      remoteRef:
        key: "infraflux-prod/velero-minio"
        property: "secret_access_key"
