apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway-helm
      version: 1.0.x
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system
  values: {}
