---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  cidrs:
    - cidr: "{{ cilium_config.lb_ip_range.split('-')[0] }}/28"
  serviceSelector:
    matchLabels: {}  # All LoadBalancer services
