---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 61.7.0
    helm:
      values: |
        grafana:
          defaultDashboardsEnabled: true
        prometheus:
          retention: 7d
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
