apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 10m
  chart:
    spec:
      chart: kyverno
      version: 3.2.6
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    workload:
      namespace: kyverno
    admissionController:
      replicas: 2
    backgroundController:
      replicas: 1
    cleanupController:
      replicas: 1
