---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 12h
  chart:
    spec:
      chart: authentik
      version: ">=2025.6.2"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: authentik-helm-chart-value-overrides
      valuesKey: values.yaml
      optional: false
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  install:
    timeout: 10m
