apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 15m
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      version: 1.15.x
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: cilium-helm-values
      valuesKey: values.yaml
