services:
  zilean:
    image: ipromknight/zilean:latest
    restart: unless-stopped
    container_name: zilean
    hostname: zilean
    tty: true
    ports:
      - "8182:8181"
    volumes:
      - ./data:/app/data
      - ./tmp:/tmp
    healthcheck:
      test: curl --connect-timeout 10 --silent --show-error --fail http://localhost:8182/healthchecks/ping
      timeout: 60s
      interval: 30s
      retries: 10
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.zilean-http.entrypoints: web
      traefik.http.routers.zilean-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker,authentik@docker
      traefik.http.routers.zilean-http.rule: Host(`zilean.binghzal.com`)
      traefik.http.routers.zilean-http.service: zilean
      traefik.http.routers.zilean.entrypoints: websecure
      traefik.http.routers.zilean.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker,authentik@docker
      traefik.http.routers.zilean.rule: Host(`zilean.binghzal.com`)
      traefik.http.routers.zilean.service: zilean
      traefik.http.routers.zilean.tls.certresolver: cfdns
      traefik.http.routers.zilean.tls.options: securetls@file
      traefik.http.services.zilean.loadbalancer.server.port: 8182

networks:
  saltbox:
    external: true
