---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: infraflux-security
    toolkit.fluxcd.io/tenant: infraflux-team
  annotations:
    config.kubernetes.io/local-config: "true"