apiVersion: v1
kind: ConfigMap
metadata:
  name: sealed-secrets-helm-chart-value-overrides
  namespace: sealed-secrets
data:
  values.yaml: |
    fullnameOverride: sealed-secrets-controller
    
    controller:
      create: true
      
    serviceAccount:
      create: true
      name: sealed-secrets-controller
      
    rbac:
      create: true
      
    # Security settings
    securityContext:
      fsGroup: 65534
      runAsUser: 1001
      runAsNonRoot: true
      
    # Resource limits
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
        
    # Service configuration
    service:
      type: ClusterIP
      port: 8080
      
    # Metrics
    metrics:
      serviceMonitor:
        enabled: false
        
    # Additional security
    podSecurityContext:
      fsGroup: 65534
      runAsUser: 1001
      runAsNonRoot: true
      
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001