apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 12h
  chart:
    spec:
      chart: sealed-secrets
      version: ">=2.16.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami-labs
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: sealed-secrets-helm-chart-value-overrides
      valuesKey: values.yaml
      optional: false
  upgrade:
    remediation:
      retries: 3