---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-s3-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: SecretStore
  target:
    name: minio-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: "infraflux-prod/MinIO Credentials"
        property: "access_key_id"
    - secretKey: aws_secret_access_key
      remoteRef:
        key: "infraflux-prod/MinIO Credentials"
        property: "secret_access_key"
    - secretKey: aws_s3_endpoint
      remoteRef:
        key: "infraflux-prod/MinIO Credentials"
        property: "endpoint"
