---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword
  namespace: external-secrets
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          serviceAccountToken:
            name: onepassword-service-account
            key: token
