apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
spec:
  destination: { server: https://kubernetes.default.svc, namespace: onepassword }
  source:
    repoURL: https://1password.github.io/connect-helm-charts
    chart: connect
    targetRevision: 1.14.0
    helm:
      values: |
        connect:
          serviceType: ClusterIP
        operator:
          enabled: false
  syncPolicy: { automated: { prune: true, selfHeal: true } }
