proxmox_vm_ram: 4096
proxmox_vm_cores: 2
proxmox_vm_disk_size_gb: 30
proxmox_vm_network_bridge: vmbr0
proxmox_vm_vlan_tag: ""
proxmox_storage: local-lvm
proxmox_node_default: pve
cloud_image: "ubuntu-22.04"
cloud_image_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
cloud_image_alias: "jammy-amd64"
ci_user: ubuntu
ci_ssh_authorized_keys: []
ci_dns_servers: ["1.1.1.1", "8.8.8.8"]
ci_packages: ["qemu-guest-agent", "curl"]
admin_ssh_user: ubuntu
admin_ssh_key: ""
proxmox_host_username: root@pam
proxmox_host_password: changeme
proxmox_api_host: 10.0.0.69
proxmox_manage_template: false
template_name: template-ubuntu
