apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: infraflux
    app.kubernetes.io/managed-by: flux
spec:
  group: velero.io
  names:
    kind: Backup
    listKind: BackupList
    plural: backups
    singular: backup
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: "Backup is a Velero resource that represents the capture of Kubernetes cluster state at a point in time"
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            description: 'BackupSpec defines the specification for a Velero backup.'
            type: object
          status:
            description: 'BackupStatus captures the current status of a Velero backup.'
            type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schedules.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: infraflux
    app.kubernetes.io/managed-by: flux
spec:
  group: velero.io
  names:
    kind: Schedule
    listKind: ScheduleList
    plural: schedules
    singular: schedule
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: "Schedule is a Velero resource that represents a pre-scheduled or periodic Backup that should be run."
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            description: 'ScheduleSpec defines the specification for a Velero schedule'
            type: object
            required:
            - schedule
            - template
            properties:
              schedule:
                description: 'Schedule is a Cron expression defining when to run the Backup.'
                type: string
              template:
                description: 'Template is the definition of the Backup to be run on the provided schedule'
                type: object
          status:
            description: 'ScheduleStatus captures the current state of a Velero schedule'
            type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restores.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: infraflux
    app.kubernetes.io/managed-by: flux
spec:
  group: velero.io
  names:
    kind: Restore
    listKind: RestoreList
    plural: restores
    singular: restore
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: "Restore is a Velero resource that represents the application of resources from a Velero backup to a target Kubernetes cluster."
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            description: 'RestoreSpec defines the specification for a Velero restore.'
            type: object
            required:
            - backupName
            properties:
              backupName:
                description: 'BackupName is the unique name of the Velero backup to restore from.'
                type: string
          status:
            description: 'RestoreStatus captures the current status of a Velero restore'
            type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backupstoragelocations.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: infraflux
    app.kubernetes.io/managed-by: flux
spec:
  group: velero.io
  names:
    kind: BackupStorageLocation
    listKind: BackupStorageLocationList
    plural: backupstoragelocations
    shortNames:
    - bsl
    singular: backupstoragelocation
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: "BackupStorageLocation is a location where Velero stores backup objects"
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            description: 'BackupStorageLocationSpec defines the specification for a Velero BackupStorageLocation.'
            type: object
            required:
            - provider
            - objectStorage
            properties:
              provider:
                description: 'Provider is the provider of the backup storage.'
                type: string
              objectStorage:
                description: 'ObjectStorageLocation specifies the settings necessary to connect to a provider''s object storage.'
                type: object
          status:
            description: 'BackupStorageLocationStatus describes the current status of a Velero BackupStorageLocation.'
            type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotlocations.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: infraflux
    app.kubernetes.io/managed-by: flux
spec:
  group: velero.io
  names:
    kind: VolumeSnapshotLocation
    listKind: VolumeSnapshotLocationList
    plural: volumesnapshotlocations
    shortNames:
    - vsl
    singular: volumesnapshotlocation
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: "VolumeSnapshotLocation is a location where Velero stores volume snapshots."
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            description: 'VolumeSnapshotLocationSpec defines the specification for a Velero VolumeSnapshotLocation.'
            type: object
            required:
            - provider
            properties:
              provider:
                description: 'Provider is the provider of the volume storage.'
                type: string
          status:
            description: 'VolumeSnapshotLocationStatus describes the current status of a Velero VolumeSnapshotLocation.'
            type: object