apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: control-plane-template
  namespace: default
spec:
  template:
    spec:
      # The Proxmox VM template/ID that has Talos ISO/disk configured; replace with your template ID
      templateID: 500
      sourceNode: pve
      format: qcow2
      full: true
      memoryMiB: 4096
      numCores: 2
      numSockets: 1
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 30
      network:
        default:
          bridge: vmbr0
          model: virtio
      # Optional cloud-init style customization is not used; Talos bootstrap provider handles ignition/config
