apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: proxmox-cluster
  namespace: default
spec:
  credentialsRef:
  name: proxmox-credentials
  namespace: capi-system
  # Allowed Proxmox node names where VMs can be scheduled
  allowedNodes:
    - pve
  # Control plane endpoint must be routable and reserved
  controlPlaneEndpoint:
    host: 10.0.1.50
    port: 6443
  dnsServers:
    - 1.1.1.1
    - 8.8.8.8
  ipv4Config:
    addresses:
      - 10.0.1.210-10.0.1.219
    gateway: 10.0.0.1
    prefix: 20
