apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: TalosControlPlane
metadata:
  name: mgmt-proxmox-cp
  namespace: default
spec:
  replicas: 1
  version: v1.31.4
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachineTemplate
    name: control-plane-template
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      # Optional Talos patches go here (e.g., external CCM, kube-vip, extra kernel args)
      # strategicPatches:
      #   - |
      #     - op: add
      #       path: /cluster/externalCloudProvider
      #       value:
      #         enabled: true
      #         manifests:
      #           - https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml
