apiVersion: v1
kind: List
items:
  - apiVersion: cilium.io/v2alpha1
    kind: CiliumLoadBalancerIPPool
    metadata:
      name: lb-pool
    spec:
      blocks:
        - start: 10.0.15.100
          stop: 10.0.15.250
  - apiVersion: cilium.io/v2alpha1
    kind: CiliumL2AnnouncementPolicy
    metadata:
      name: l2-policy
    spec:
      externalIPs: true
      loadBalancerIPs: true
