# Packer Variables for pve
# Generated by InfraFlux Ansible automation

# Proxmox connection
proxmox_api_url          = "https://10.0.0.69:8006/api2/json"
proxmox_api_token_id     = "root@pam!infraflux"
proxmox_api_token_secret = "0c93d1fd-c06c-4621-ae2c-728196380302"
proxmox_node             = "pve"

# Storage configuration
proxmox_storage_pool = "bigdisk"
proxmox_iso_storage  = "synology"

# Talos configuration
talos_version  = "v1.6.0"
talos_iso_file = "talos_nocloud-amd64.iso"

# VM template configuration
vm_id             = 9000
vm_name           = "talos-v1.6.0-template"
vm_cpu_cores      = 2
vm_memory         = 4096
vm_disk_size      = "20G"
vm_network_bridge = "vmbr0"