apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/
namespace: kyverno
spec:
  interval: 10m
  path: ./platform/addons/kyverno/manifests
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: bootstrap-helmrepos
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno-background-controller
      namespace: kyverno
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno-cleanup-controller
      namespace: kyverno
