apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-helm-values
  namespace: apps
data:
  values.yaml: |
    replicaCount: 2
    ui:
      color: "#3465a4"
    ingress:
      enabled: true
      className: cilium
      hosts:
        - host: podinfo.local
          paths:
            - path: /
              pathType: Prefix
