# Create directories for RKE2 and kube-vip manifests
- name: Create RKE2 server directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - "/var/lib/rancher"
    - "/var/lib/rancher/rke2"
    - "/var/lib/rancher/rke2/server"
    - "/var/lib/rancher/rke2/server/manifests"
  when: inventory_hostname in groups['servers']

# Copy kube-vip to server 1 manifest folder for auto deployment at bootstrap
- name: Deploy Kube VIP Configuration
  ansible.builtin.template:
    src: templates/kube-vip-config.j2
    dest: /var/lib/rancher/rke2/server/manifests/kube-vip.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]
