apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetragon
  namespace: argocd
  labels:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/component: security
spec:
  project: platform
  source:
    repoURL: https://helm.cilium.io/
    chart: tetragon
    targetRevision: 1.2.0
    helm:
      releaseName: tetragon
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
