# Download and run the RKE2 installer script
- name: Download RKE2 installer script
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2-install.sh
    mode: '0755'

# Install RKE2 using the official installer
- name: Install RKE2
  ansible.builtin.shell: |
    INSTALL_RKE2_VERSION="{{ rke2_version }}" sh /tmp/rke2-install.sh
  environment:
    INSTALL_RKE2_TYPE: "{{ 'server' if inventory_hostname in groups['servers'] else 'agent' }}"
  changed_when: true

# Clean up installer script
- name: Remove installer script
  ansible.builtin.file:
    path: /tmp/rke2-install.sh
    state: absent
