# Gateway API CRDs
# This installs the standard Gateway API CRDs required by Cilium
---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/kubernetes-sigs/gateway-api.git
  ref:
    tag: v1.2.0
  path: config/crd/standard
  prune: true
  wait: true
