apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: trivy
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - trivy.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: infraflux
      app.kubernetes.io/managed-by: flux

images:
  - name: aquasec/trivy-operator
    newTag: "0.15.1"
  - name: aquasec/trivy
    newTag: "0.45.1"