# Development Environment Configuration

# Environment-specific overrides for development
environment:
  name: "dev"
  domain: "dev.platform.local"

# Cluster configuration overrides
clusterOverrides:
  # Smaller cluster for development
  name: "infraflux-dev"
  controlplane_count: 1
  worker_count: 0
  allow_scheduling_on_controlplane: true
  nodes:
    controlPlane:
      count: 1
      cpu: 2
      memory: "4Gi"
      disk: "50Gi"
    worker:
      count: 2
      cpu: 4
      memory: "8Gi"
      disk: "100Gi"

# Infrastructure component overrides
infrastructureOverrides:
  # Use staging certificates in dev
  certManager:
    config:
      defaultIssuer: "letsencrypt-staging"

  # Reduced monitoring retention
  monitoring:
    prometheus:
      retention: "7d"
      storage: "20Gi"

  # Simpler Cilium configuration
  cilium:
    config:
      encryption: false
      hubble:
        enabled: true
        ui: false # Disable UI in dev to save resources

# Development-specific features
featureOverrides:
  # Enable useful dev features
  chaosEngineering: true
  imageScanning: true
  ciliumMesh: false
  tetragon: true

# Relaxed security for development
securityOverrides:
  podSecurity:
    enforce: "privileged"
    audit: "baseline"
    warn: "baseline"
  networkPolicies: true
  encryptionAtRest: false # Dev environment

# Smaller resource quotas for dev
resourceOverrides:
  defaultQuota:
    requests:
      cpu: "2"
      memory: "4Gi"
      storage: "20Gi"
    limits:
      cpu: "4"
      memory: "8Gi"

# Proxmox configuration for dev environment
proxmox:
  api_url: "https://proxmox.local:8006/api2/json"
  user: "terraform@pve"
  target_node: "pve"
  storage: "local-lvm"
  tls_insecure: true

# Talos configuration
talos:
  template_id: 9000
  version: "v1.6.0"

# Network configuration
network:
  bridge: "vmbr0"
  vlan_tag: null
  subnet: "192.168.1.0/24"
  base_ip: "192.168.1."
  ip_start: 100
  gateway: "192.168.1.1"
  dns_servers:
    - "1.1.1.1"
    - "8.8.8.8"
