# Production Environment Configuration
# High-availability multi-node cluster for production workloads

cluster:
  name: "infraflux-prod"
  controlplane_count: 3
  worker_count: 3
  allow_scheduling_on_controlplane: false

proxmox:
  api_url: "https://proxmox.local:8006/api2/json"
  user: "terraform@pve"
  target_node: "pve"
  storage: "local-lvm"
  tls_insecure: true

talos:
  template_id: 9000
  version: "v1.6.0"

network:
  bridge: "vmbr0"
  vlan_tag: 100 # Production VLAN
  subnet: "10.0.100.0/24"
  base_ip: "10.0.100."
  ip_start: 10
  gateway: "10.0.100.1"
  dns_servers:
    - "10.0.1.1"
    - "10.0.1.2"
  cluster_vip: "10.0.100.100" # Virtual IP for HA

nodes:
  controlplane:
    cpu_cores: 4
    memory_mb: 8192
    disk_size_gb: 100
  worker:
    cpu_cores: 8
    memory_mb: 16384
    disk_size_gb: 200

features:
  cilium:
    enabled: true
    cluster_mesh: true
    hubble: true
    tetragon: true
    bgp: true
    encryption: "wireguard"

  monitoring:
    enabled: true
    prometheus: true
    grafana: true
    alertmanager: true
    loki: true

  cert_manager:
    enabled: true
    cluster_issuer: "letsencrypt-prod"

  argocd:
    enabled: true
    repo_url: "https://github.com/binGhzal/PlatformNorthStar"
    ha: true

  backup:
    enabled: true
    schedule: "0 2 * * *"
    retention: "30d"

security:
  pod_security_standards: "restricted"
  network_policies: true
  encryption_at_rest: true
  image_scanning: true
  compliance_scanning: true

storage:
  longhorn:
    enabled: true
    replicas: 3
    backup_target: "nfs://backup.local/longhorn"
