# Staging Environment Configuration

# Environment-specific overrides for staging
environment:
  name: "staging"
  domain: "staging.platform.local"

# Cluster configuration overrides
clusterOverrides:
  # Medium cluster for staging
  name: "infraflux-staging"
  controlplane_count: 3
  worker_count: 2
  allow_scheduling_on_controlplane: false
  nodes:
    controlPlane:
      count: 3
      cpu: 4
      memory: "8Gi"
      disk: "100Gi"
    worker:
      count: 2
      cpu: 8
      memory: "16Gi"
      disk: "200Gi"

# Infrastructure component overrides
infrastructureOverrides:
  # Use staging certificates
  certManager:
    config:
      defaultIssuer: "letsencrypt-staging"

  # Medium monitoring retention
  monitoring:
    prometheus:
      retention: "30d"
      storage: "100Gi"

  # Production-like Cilium configuration
  cilium:
    config:
      encryption: true
      hubble:
        enabled: true
        ui: true

# Staging-specific features
featureOverrides:
  chaosEngineering: false
  imageScanning: true
  ciliumMesh: false
  tetragon: true

# Standard security for staging
securityOverrides:
  podSecurity:
    enforce: "baseline"
    audit: "baseline"
    warn: "restricted"
  networkPolicies: true
  encryptionAtRest: true

# Medium resource quotas for staging
resourceOverrides:
  defaultQuota:
    requests:
      cpu: "8"
      memory: "16Gi"
      storage: "100Gi"
    limits:
      cpu: "16"
      memory: "32Gi"

# Proxmox configuration for staging environment
proxmox:
  api_url: "https://proxmox.local:8006/api2/json"
  user: "terraform@pve"
  target_node: "pve"
  storage: "local-lvm"
  tls_insecure: true

# Talos configuration
talos:
  template_id: 9000
  version: "v1.6.0"

# Network configuration
network:
  bridge: "vmbr0"
  vlan_tag: 200 # Separate VLAN for staging
  subnet: "192.168.200.0/24"
  base_ip: "192.168.200."
  ip_start: 100
  gateway: "192.168.200.1"
  dns_servers:
    - "1.1.1.1"
    - "8.8.8.8"
