apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-values
  namespace: podinfo
data:
  values.yaml: |
    replicaCount: 1
    ui:
      color: "#0ea5e9"
    ingress:
      enabled: true
      className: cilium
      hosts:
        - host: podinfo.local
          paths:
            - path: /
              pathType: Prefix
