# Cilium values - kube-proxy free + Gateway API
kubeProxyReplacement: true
gatewayAPI:
  enabled: true
  hostnetwork: true
bgpControlPlane:
  enabled: true
hubble:
  enabled: true
  metrics:
    enabled: true
ipam:
  mode: kubernetes
