---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-config
  namespace: flux-system
data:
  values.yaml: |
    provider: cloudflare

    sources:
      - gateway-httproute  # Gateway API support
      - gateway-grpcroute
      - service
      - ingress

    cloudflare:
      proxied: true  # Enable CDN/DDoS protection by default
      dnsRecordsPerPage: 5000  # Optimize for Cloudflare's API limits

    domainFilters:
      - "{{ cloudflare_domain }}"  # Will be replaced with actual domain

    policy: sync
    registry: txt
    txtOwnerId: "infraflux-k8s"
    txtPrefix: "external-dns-"

    interval: 1m
    batchChangeSize: 1000
    batchChangeInterval: 10s

    # Enhanced monitoring
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false  # Set to true if Prometheus operator is available
        additionalLabels:
          monitoring: "true"

    # Performance optimizations
    extraArgs:
      - --cloudflare-dns-records-per-page=5000
      - --events-burst-sync=true

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token

    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi

    rbac:
      create: true

    serviceAccount:
      create: true
      name: external-dns

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      capabilities:
        drop: ["ALL"]

    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
      fsGroup: 65534

    logLevel: info
    logFormat: json
