apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: example-app
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - helmrelease.yaml

commonLabels:
  app.kubernetes.io/name: example-app
  app.kubernetes.io/managed-by: flux