#!/bin/bash

# InfraFlux Application Configuration Script
# This script dynamically enables/disables applications based on cluster-config.yaml

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PROJECT_ROOT/config/cluster-config.yaml"
BASE_KUSTOMIZATION="$PROJECT_ROOT/cluster/base/kustomization.yaml"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $*"
}

error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

warn() {
    echo -e "${YELLOW}[WARNING]${NC} $*"
}

# Function to get config value
get_config_value() {
    local key="$1"
    yq eval ".data.${key}" "$CONFIG_FILE" 2>/dev/null || echo "false"
}

# Function to enable/disable resource in kustomization
toggle_resource() {
    local resource_path="$1"
    local enabled="$2"
    local kustomization_file="$3"
    
    if [[ "$enabled" == "true" ]]; then
        # Enable resource (uncomment)
        if grep -q "^[[:space:]]*#[[:space:]]*-[[:space:]]*${resource_path}" "$kustomization_file"; then
            sed -i.bak "s|^[[:space:]]*#[[:space:]]*-[[:space:]]*${resource_path}|  - ${resource_path}|" "$kustomization_file"
            log "Enabled: $resource_path"
        elif ! grep -q "^[[:space:]]*-[[:space:]]*${resource_path}" "$kustomization_file"; then
            # Add if not present
            sed -i.bak "/^resources:/a\\
  - ${resource_path}" "$kustomization_file"
            log "Added: $resource_path"
        fi
    else
        # Disable resource (comment out)
        if grep -q "^[[:space:]]*-[[:space:]]*${resource_path}" "$kustomization_file"; then
            sed -i.bak "s|^[[:space:]]*-[[:space:]]*${resource_path}|  # - ${resource_path}|" "$kustomization_file"
            log "Disabled: $resource_path"
        fi
    fi
}

main() {
    log "Starting InfraFlux application configuration..."
    
    # Check if config file exists
    if [[ ! -f "$CONFIG_FILE" ]]; then
        error "Configuration file not found: $CONFIG_FILE"
        exit 1
    fi
    
    # Backup kustomization file
    cp "$BASE_KUSTOMIZATION" "${BASE_KUSTOMIZATION}.backup"
    
    log "Reading configuration from: $CONFIG_FILE"
    
    # AI/ML Platform
    enable_ai_ml=$(get_config_value "enable_ai_ml")
    enable_ollama=$(get_config_value "enable_ollama") 
    enable_open_webui=$(get_config_value "enable_open_webui")
    enable_jupyterhub=$(get_config_value "enable_jupyterhub")
    
    # Media & Entertainment
    enable_jellyfin=$(get_config_value "enable_jellyfin")
    enable_sonarr=$(get_config_value "enable_sonarr")
    enable_radarr=$(get_config_value "enable_radarr")
    enable_prowlarr=$(get_config_value "enable_prowlarr")
    enable_immich=$(get_config_value "enable_immich")
    
    # Infrastructure & Services
    enable_gpu_support=$(get_config_value "enable_gpu_support")
    enable_external_dns=$(get_config_value "enable_external_dns")
    enable_public_ingress=$(get_config_value "enable_public_ingress")
    enable_cloudflare_automation=$(get_config_value "enable_cloudflare_automation")
    
    # Development Tools
    enable_harbor=$(get_config_value "enable_harbor")
    enable_code_server=$(get_config_value "enable_code_server")
    
    log "Configuring application resources..."
    
    # Configure AI/ML Platform
    if [[ "$enable_ai_ml" == "true" || "$enable_ollama" == "true" || "$enable_open_webui" == "true" ]]; then
        toggle_resource "applications/ai-ml" "true" "$BASE_KUSTOMIZATION"
    else
        toggle_resource "applications/ai-ml" "false" "$BASE_KUSTOMIZATION"
    fi
    
    # Configure Media Platform  
    if [[ "$enable_jellyfin" == "true" || "$enable_sonarr" == "true" || "$enable_radarr" == "true" ]]; then
        toggle_resource "applications/media" "true" "$BASE_KUSTOMIZATION"
    else
        toggle_resource "applications/media" "false" "$BASE_KUSTOMIZATION"
    fi
    
    # Configure GPU Infrastructure
    toggle_resource "infrastructure/gpu" "$enable_gpu_support" "$BASE_KUSTOMIZATION"
    
    # Configure DNS Services
    toggle_resource "dns" "$enable_external_dns" "$BASE_KUSTOMIZATION"
    
    # Configure Automation Services
    toggle_resource "automation" "$enable_cloudflare_automation" "$BASE_KUSTOMIZATION"
    
    # Generate application-specific patches
    log "Generating conditional patches..."
    
    # Create patches directory if it doesn't exist
    mkdir -p "$PROJECT_ROOT/cluster/base/patches"
    
    # Generate AI/ML patches
    cat > "$PROJECT_ROOT/cluster/base/patches/ai-ml-conditional.yaml" << EOF
# AI/ML Stack Conditional Configuration
# Generated by configure-apps.sh based on cluster-config.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: applications
spec:
  replicas: $([ "$enable_ollama" == "true" ] && echo "1" || echo "0")

---
apiVersion: apps/v1  
kind: Deployment
metadata:
  name: open-webui
  namespace: applications
spec:
  replicas: $([ "$enable_open_webui" == "true" ] && echo "1" || echo "0")
EOF

    # Generate media patches
    cat > "$PROJECT_ROOT/cluster/base/patches/media-conditional.yaml" << EOF
# Media Stack Conditional Configuration
# Generated by configure-apps.sh based on cluster-config.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: applications
spec:
  replicas: $([ "$enable_jellyfin" == "true" ] && echo "1" || echo "0")
EOF

    # Generate DNS patches
    cat > "$PROJECT_ROOT/cluster/base/patches/dns-conditional.yaml" << EOF
# DNS Services Conditional Configuration
# Generated by configure-apps.sh based on cluster-config.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-cloudflare
  namespace: kube-system
spec:
  replicas: $([ "$enable_external_dns" == "true" ] && echo "1" || echo "0")
EOF

    # Generate automation patches
    cat > "$PROJECT_ROOT/cluster/base/patches/automation-conditional.yaml" << EOF
# Automation Services Conditional Configuration
# Generated by configure-apps.sh based on cluster-config.yaml

apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-dns-sync
  namespace: kube-system
spec:
  suspend: $([ "$enable_cloudflare_automation" == "true" ] && echo "false" || echo "true")

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-security-sync
  namespace: kube-system
spec:
  suspend: $([ "$enable_cloudflare_automation" == "true" ] && echo "false" || echo "true")
EOF

    # Clean up backup files
    rm -f "${BASE_KUSTOMIZATION}.bak"
    
    success "Application configuration completed!"
    
    # Summary
    log "Configuration Summary:"
    echo "  AI/ML Platform: $([ "$enable_ai_ml" == "true" ] && echo "✅ Enabled" || echo "❌ Disabled")"
    echo "  Media Platform: $([ "$enable_jellyfin" == "true" ] && echo "✅ Enabled" || echo "❌ Disabled")"  
    echo "  GPU Support: $([ "$enable_gpu_support" == "true" ] && echo "✅ Enabled" || echo "❌ Disabled")"
    echo "  External DNS: $([ "$enable_external_dns" == "true" ] && echo "✅ Enabled" || echo "❌ Disabled")"
    echo "  Public Access: $([ "$enable_public_ingress" == "true" ] && echo "✅ Enabled" || echo "❌ Disabled")"
    echo "  Cloudflare Automation: $([ "$enable_cloudflare_automation" == "true" ] && echo "✅ Enabled" || echo "❌ Disabled")"
    
    log "Run 'kustomize build cluster/base' to verify the configuration"
    log "Run './deploy.sh apps' to apply the changes to your cluster"
}

# Show help
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    cat << EOF
InfraFlux Application Configuration Script

This script dynamically enables/disables applications in your InfraFlux cluster
based on the settings in config/cluster-config.yaml.

Usage: $0 [OPTIONS]

Options:
  --help, -h    Show this help message
  --dry-run     Show what would be changed without making changes
  --restore     Restore from backup

Examples:
  $0              # Configure applications based on current config
  $0 --dry-run    # Preview changes without applying them
  $0 --restore    # Restore previous configuration

Configuration is read from: config/cluster-config.yaml
Supported application flags:
  - enable_ai_ml, enable_ollama, enable_open_webui
  - enable_jellyfin, enable_sonarr, enable_radarr
  - enable_gpu_support, enable_external_dns
  - enable_public_ingress

EOF
    exit 0
fi

# Dry run mode
if [[ "${1:-}" == "--dry-run" ]]; then
    log "DRY RUN MODE - No changes will be made"
    # Set dry run flag and continue
    DRY_RUN=true
fi

# Restore mode
if [[ "${1:-}" == "--restore" ]]; then
    if [[ -f "${BASE_KUSTOMIZATION}.backup" ]]; then
        cp "${BASE_KUSTOMIZATION}.backup" "$BASE_KUSTOMIZATION"
        success "Configuration restored from backup"
    else
        error "No backup file found"
        exit 1
    fi
    exit 0
fi

main "$@"