apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flux-notifications
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - providers.yaml
  - alerts.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: flux-notifications
      app.kubernetes.io/managed-by: flux