# Update package cache and install required packages
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install required packages
  ansible.builtin.package:
    name:
      - curl
      - wget
      - systemd
      - iptables
      - ipset
    state: present

# Ensure required kernel modules are loaded
- name: Load br_netfilter module
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present

- name: Load overlay module
  ansible.builtin.modprobe:
    name: overlay
    state: present

- name: Ensure kernel modules are loaded at boot
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/rke2.conf
    line: "{{ item }}"
    create: true
  loop:
    - br_netfilter
    - overlay

# Enable IPv4 forwarding
- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
  tags: sysctl

# Enable IPv6 forwarding
- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  tags: sysctl

# Disable swap
- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: false
  ignore_errors: true

- name: Remove swap from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent