---
# Auto-generated RKE2 configuration variables
# Generated by Terraform on ${timestamp()}
# TODO: InfraFlux Refactoring Tasks
# - [x] Added external_endpoint variable for external cluster access
# - [ ] Consider adding more network-related configurations here
# - [ ] Add variables for custom certificate SANs

os: "${os}"
arch: "${arch}"

# User Configuration
ansible_user: "${ansible_user}"

vip: "${vip}"
vip_interface: "${vip_interface}"

# External endpoint for accessing cluster from outside internal network
# If empty, will use VIP for all kubeconfig generation
external_endpoint: "${external_endpoint}"

metallb_version: "${metallb_version}"
lb_range: "${lb_range}"
lb_pool_name: "${lb_pool_name}"

ansible_become: true
ansible_become_method: sudo

################################################################################
# RKE2 Configuration Options
################################################################################
kube_vip_version: "${kube_vip_version}"
rke2_version: "${rke2_version}"
rke2_install_dir: "/usr/local/bin"
