apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: production-environment
  annotations:
    config.kubernetes.io/local-config: "true"

# Production environment-specific configurations
resources:
  - policies.yaml
  - security.yaml
  - resource-limits.yaml

labels:
  - includeSelectors: true
    pairs:
      environment: production
      app.kubernetes.io/managed-by: flux