# Default Infrastructure Configuration

# This file contains the default values for all infrastructure components.
# These values can be overridden by environment-specific or cluster-specific configurations.

# Global Configuration
global:
  # Domain configuration
  domain: "platform.local"

  # Container registry
  registry:
    url: "registry.platform.local"
    namespace: "platform"

  # Git configuration
  git:
    infraRepo: "https://github.com/binGhzal/infraflux"
    appsRepo: "https://github.com/binGhzal/PlatformNorthStar"
    branch: "main"

# Cluster Configuration
cluster:
  # Kubernetes version
  kubernetesVersion: "v1.29.0"

  # Talos configuration
  talos:
    version: "v1.6.0"
    image: "factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba"

  # Network configuration
  network:
    clusterDomain: "cluster.local"
    serviceCIDR: "10.96.0.0/12"
    podCIDR: "10.244.0.0/16"
    dnsDomain: "platform.local"

  # Node configuration
  nodes:
    controlPlane:
      count: 3
      cpu: 4
      memory: "8Gi"
      disk: "100Gi"
    worker:
      count: 3
      cpu: 8
      memory: "16Gi"
      disk: "200Gi"

# Infrastructure Components
infrastructure:
  # Cilium CNI Configuration
  cilium:
    enabled: true
    version: "1.15.0"
    config:
      tunnel: "vxlan"
      encryption: false
      hubble:
        enabled: true
        ui: true
      gatewayAPI: true
      loadBalancer:
        mode: "dsr"
        acceleration: "native"

  # cert-manager Configuration
  certManager:
    enabled: true
    version: "v1.13.0"
    config:
      defaultIssuer: "letsencrypt-staging"
      acme:
        email: "admin@platform.local"
        server: "https://acme-staging-v02.api.letsencrypt.org/directory"

  # External DNS Configuration
  externalDns:
    enabled: true
    version: "0.14.0"
    config:
      provider: "cloudflare"
      domainFilters: []
      txtOwnerId: "platform"

  # Monitoring Configuration
  monitoring:
    enabled: true
    prometheus:
      version: "v2.48.0"
      retention: "30d"
      storage: "50Gi"
    grafana:
      version: "10.2.0"
      admin:
        user: "admin"
        # Password should be set in secrets
    alertmanager:
      version: "v0.26.0"
      retention: "120h"

  # ArgoCD Configuration
  argocd:
    enabled: true
    version: "v2.9.0"
    config:
      server:
        insecure: false
        grpc:
          web: true
      repositories:
        - url: "https://github.com/binGhzal/infraflux"
          name: "infraflux"
        - url: "https://github.com/binGhzal/PlatformNorthStar"
          name: "platform-north-star"
      projects:
        - name: "platform"
          description: "Platform infrastructure components"
          sourceRepos:
            - "https://github.com/binGhzal/infraflux"
          destinations:
            - namespace: "*"
              server: "https://kubernetes.default.svc"
        - name: "applications"
          description: "Application workloads"
          sourceRepos:
            - "https://github.com/binGhzal/PlatformNorthStar"
          destinations:
            - namespace: "*"
              server: "https://kubernetes.default.svc"

# Security Configuration
security:
  # Pod Security Standards
  podSecurity:
    enforce: "baseline"
    audit: "baseline"
    warn: "baseline"

  # Network Policies
  networkPolicies:
    defaultDeny: true
    allowDNS: true
    allowKubeAPI: true

  # RBAC Configuration
  rbac:
    enabled: true
    aggregateClusterRoles: true

# Storage Configuration
storage:
  # Default storage class
  defaultClass: "longhorn"

  # Longhorn configuration
  longhorn:
    enabled: true
    version: "v1.5.0"
    config:
      defaultReplicas: 3
      storageOverProvisioningPercentage: 200
      storageMinimalAvailablePercentage: 25

# Backup Configuration
backup:
  enabled: true
  etcd:
    schedule: "0 2 * * *" # Daily at 2 AM
    retention: "30" # Keep 30 backups
  velero:
    enabled: false
    provider: "aws"
    bucket: "platform-backups"

# Resource Quotas and Limits
resources:
  # Default resource quotas for namespaces
  defaultQuota:
    requests:
      cpu: "4"
      memory: "8Gi"
      storage: "50Gi"
    limits:
      cpu: "8"
      memory: "16Gi"
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"

  # Default limit ranges
  defaultLimits:
    containers:
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      defaultLimit:
        cpu: "500m"
        memory: "512Mi"
      maxLimit:
        cpu: "2"
        memory: "4Gi"

# Feature Flags
features:
  # Enable multi-cluster support
  multiCluster: false

  # Enable service mesh
  serviceMesh: false

  # Enable image scanning
  imageScanning: false

  # Enable cost monitoring
  costMonitoring: false

  # Enable chaos engineering
  chaosEngineering: false
