---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  # Infrastructure controllers
  - cilium-repo.yaml
  - jetstack-repo.yaml
  - sealed-secrets-repo.yaml
  
  # Application repositories
  - prometheus-repo.yaml
  - grafana-repo.yaml