apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.15.x
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    kubeProxyReplacement: true
    k8sServiceHost: ${CONTROL_PLANE_ENDPOINT} # optionally set by overlay
    k8sServicePort: 6443
