apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-providers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: platform
  source:
    repoURL: https://github.com/binGhzal/infraflux
    targetRevision: main
    path: clusters/mgmt/providers
  destination:
    server: https://kubernetes.default.svc
    namespace: capi-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
