apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  interval: 10m
  path: ./recipes/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: infraflux
    namespace: flux-system
