# Ensure facts are gathered first
- name: Gather facts
  ansible.builtin.setup:
  tags: always

# Update package cache and install required packages
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install required packages
  ansible.builtin.package:
    name:
      - curl
      - wget
      - systemd
      - iptables
      - ipset
    state: present

# Ensure required kernel modules are loaded
- name: Load required kernel modules for Cilium eBPF
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay
    - ip_tables
    - iptable_nat
    - xt_socket
    - xt_bpf
    - sch_bpf
  become: true

- name: Ensure kernel modules are loaded at boot
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/rke2.conf
    line: "{{ item }}"
    create: true
    mode: '0644'
  loop:
    - br_netfilter
    - overlay
    - ip_tables
    - iptable_nat
    - xt_socket
    - xt_bpf
    - sch_bpf

# Configure sysctl for eBPF optimization and networking
- name: Configure sysctl for eBPF optimization
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    reload: true
    sysctl_set: true
  loop:
    - { key: "net.ipv4.ip_forward", value: "1" }
    - { key: "net.ipv6.conf.all.forwarding", value: "1" }
    - { key: "net.core.bpf_jit_enable", value: "1" }
    - { key: "net.core.bpf_jit_kallsyms", value: "1" }
    - { key: "kernel.unprivileged_bpf_disabled", value: "1" }
    - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
  become: true

# Disable swap
- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: false
  failed_when: false

- name: Remove swap from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent
