# Ensure facts are gathered first
- name: Gather facts
  ansible.builtin.setup:
  tags: always

# Update package cache and install required packages
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install required packages
  ansible.builtin.package:
    name:
      - curl
      - wget
      - systemd
      - iptables
      - ipset
    state: present

# Ensure required kernel modules are loaded
- name: Load br_netfilter module
  ansible.builtin.shell: modprobe br_netfilter
  changed_when: false
  ignore_errors: true

- name: Load overlay module
  ansible.builtin.shell: modprobe overlay
  changed_when: false
  ignore_errors: true

- name: Ensure kernel modules are loaded at boot
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/rke2.conf
    line: "{{ item }}"
    create: true
  loop:
    - br_netfilter
    - overlay

# Enable IPv4 forwarding
- name: Enable IPv4 forwarding
  ansible.builtin.shell: |
    echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf
    sysctl -p
  changed_when: false

# Enable IPv6 forwarding
- name: Enable IPv6 forwarding
  ansible.builtin.shell: |
    echo 'net.ipv6.conf.all.forwarding = 1' >> /etc/sysctl.conf
    sysctl -p
  changed_when: false

# Disable swap
- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: false
  ignore_errors: true

- name: Remove swap from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent