# Argo CD install values
global:
  image:
    tag: v2.11.1
configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
  cmp:
    create: true
    plugins:
      ksops:
        allowFiles: true
        generate:
          command: [ "sh", "-c" ]
          args: [ "ksops -o yaml -f $ARGOCD_ENV_KSOPS_FILE" ]
