apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: kube-system
  chart:
    spec:
      chart: cilium
      version: ">=1.14.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: cilium-config
      valuesKey: values.yaml
  install:
    createNamespace: false
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3