name: CI

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  lint-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node for markdownlint
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install linters
        run: |
          npm install -g markdownlint-cli@0.39.0
          pipx install yamllint
          VERSION=v0.6.7
          curl -L "https://github.com/yannh/kubeconform/releases/download/${VERSION}/kubeconform-linux-amd64.tar.gz" | tar xz
          sudo mv kubeconform /usr/local/bin/

      - name: Markdownlint
        run: markdownlint "**/*.md" --config .markdownlint.json

      - name: Yamllint
        run: yamllint -c .yamllint .

      - name: Kubeconform
        run: |
          kubeconform -summary -strict -ignore-missing-schemas \
            -schema-location default \
            -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' \
            $(git ls-files '*.yaml' '*.yml')

  opentofu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: Validate Terraform
        run: |
          set -euo pipefail
          cd terraform
          tofu fmt -recursive -check
          tofu init -backend=false
          tofu validate
