name: infra
on:
  pull_request:
    paths: ["terraform/**", "gitops/**"]
  push:
    branches: ["main"]
    paths: ["terraform/**", "gitops/**"]

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: "1.7.5" }
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false
      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt -check
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: terraform
        run: terraform plan -no-color

  apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: "1.7.5" }
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
