creation_rules:
  - path_regex: .*(\.secret|\.enc)\.ya?ml$
    age: [ "age1d5040w4v5nx5jfeuzcagkzjnl8v5t4wvgch3u5j59xz62a2kx3hslwkemd" ]
    encrypted_regex: '^(data|stringData)$'
    # keep metadata readable for GitOps diffing
    kms: []
    gcp_kms: []
    azure_keyvault: []
    hc_vault_transit: []
