apiVersion: v1
kind: Secret
metadata:
  name: proxmox-credentials
  namespace: capmox-system
type: Opaque
stringData:
  PM_API_URL: "https://proxmox.example:8006/api2/json"
  PM_USER: "root@pam"
  PM_PASSWORD: "changeme"
