apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: argocd
type: Opaque
stringData:
  keys.txt: |
    # Paste the contents of ~/.config/sops/age/keys.txt here
    # AGE-SECRET-KEY-1...
