apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.18.x
    helm:
      values: |
        kubeProxyReplacement: "true"
        ipam:
          mode: kubernetes
        securityContext:
          capabilities:
            ciliumAgent: ["CHOWN","KILL","NET_ADMIN","NET_RAW","IPC_LOCK","SYS_ADMIN","SYS_RESOURCE","DAC_OVERRIDE","FOWNER","SETGID","SETUID"]
            cleanCiliumState: ["NET_ADMIN","SYS_ADMIN","SYS_RESOURCE"]
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        gatewayAPI:
          enabled: true
          enableAlpn: true
          enableAppProtocol: true
        ingressController:
          enabled: true
          service:
            type: LoadBalancer
        nodePort:
          enabled: true
        hostServices:
          enabled: true
        bgpControlPlane:
          enabled: true
        egressGateway:
          enabled: false
        hubble:
          enabled: true
          relay:
            enabled: true
            prometheus:
              enabled: true
              serviceMonitor:
                enabled: true
          ui:
            enabled: true
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
        encryption:
          enabled: false
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
